const services = [
  ['مدرسي','ملصقات مدرسية بصور شخصية','ثيمة لكل مادة مع الحفاظ على ملامح الوجه','A4',10,1000,'school'],['مدرسي','ملصقات مزخرفة بقص خاص','أشكال متنوعة مناسبة للقص بجهاز كاميو','A4',10,1000,'school'],['مدرسي','جدول الحصص المدرسية','جدول مخصص بالاسم والألوان والرسوم A3','A3',1,3000,'school'],['مدرسي','نشرة مدرسية','حسب الطلب: الموضوع والصف واللغة','A3',1,3000,'school'],['مدرسي','دفتر مذكرات شخصية','دفتر مقاس A5 مخطط','A5',20,1500,'school'],
  ['هدايا','صور أطفال ورقية للمغامرات','لقطات مختلفة مع قصها','A4',10,1000,'kids'],['هدايا','مجلة أطفال مصورة','محتوى وصور وتخطيط؛ عدد الصفحات حسب الطلب','A4',16,10000,'kids'],['هدايا','لوحة بورتريه شخصية','رسم حسب الطلب: فحم أو ألوان أكريلك','A4',1,5000,'portrait'],['هدايا','تحويل صورة إلى أنمي ثلاثي الأبعاد','شخصية كرتونية مع الحفاظ على الهوية','A4',1,5000,'portrait'],['هدايا','دمج الشخصية في عالم خيالي','مشهد كرتوني أو مغامرة حسب الطلب','A4',1,5000,'kids'],['هدايا','بورتريه بأسلوب قلم الرصاص','خلفية بيضاء وتفاصيل الوجه وضربات القلم','A4',1,5000,'portrait'],['هدايا','بورتريه بالأقلام الملونة الخشب','ألوان واضحة وملمس رسم فني','A4',1,5000,'portrait'],['هدايا','بورتريه بأسلوب زيتي أو أكريليك','لوحة رقمية بملمس فرشاة','A4',1,5000,'portrait'],
  ['عائلي','تحسين وترميم الصور','تحسين الإضاءة والألوان والوضوح','A3',1,10000,'restore'],['صور','صورة شخصية بخلفية بيضاء','بورتريه استوديو مع تعديل الإضاءة والزي','A6',8,3000,'portrait'],['أطفال','لوحة بيانات مولود','صورة واسم وتاريخ ووزن وطول','A4',1,5000,'kids'],['تجاري','بوستر إعلاني للسوشيال ميديا','تصميم مخصص للنشر على المنصات','A4',10,5000,'business'],['مدرسي','بوستر توعوي أو إنفوجرافيك','تنظيم المحتوى مع صور أو رموز','A3',1,3000,'school'],['تجاري','مطوية ثلاثية','وجهان وستة أعمدة','A4',50,5000,'business'],['تجاري','دفتر وصولات','دفتر وصولات ملون عادي أو مكربن، 100 ورقة','A5',10,25000,'business'],['مدرسي','بروش دبوس بنز','صورة أو كتابة','4 S',1,1500,'school'],['عائلي','بطاقة زفاف','دعوة وطباعة ملونة','A6',50,10000,'kids'],['مدرسي','شهادة التخرج','صورة مجومة مع الدرجات','A4',1,5000,'school'],['مدرسي','شهادة درجات','كارت شهادة بتصميم خاص للمدرسية','A4',100,40000,'school'],['تجاري','بطاقة مخبز','كارتات كبس عظم','A7',100,15000,'business'],['هدايا','طباعة أسماء','قص فينيل حراري وتثبيته بالمكواة العادية','A6',1,3000,'kids'],['تجاري','كرت شخصي','تصميم وطباعة حسب الطلب','A7',100,5000,'business'],['تجاري','لوحات مكتبية','لوحات الأسماء التعريفية','A7',1,5000,'business'],['تجاري','بطاقة التموين','طباعة بطاقة التموين عاج','A7',1,5000,'business'],['مؤسسات','درع كرستال','تصميم وطباعة دروع الكرستال','A5',1,15000,'business'],['مؤسسات','مجلة','إنتاج المحتوى والتصميم والطباعة','A4',40,'يحدد حسب العمل','business'],['مدارس','شهادة تقديرية','تصميم وطباعة شهادات التقدير','A4',1,500,'school'],['مؤسسات','تصميم لوكو','تصميم لوكو خاص بمؤسستك','A4',1,25000,'business'],['مدارس','الرؤية والأهداف','تصميم وطباعة على بورد خشب','A3',1,10000,'business'],['هدايا','تقويم','تقويم بصورة شخصية أو لوكو المؤسسة','A3',1,3000,'kids'],['مؤسسات','سجل','سجل مخطط ومطبوع حسب الطلب','A4',1,5000,'business'],['مؤسسات','فايل','فايل تسجيل للمدارس حسب الطلب','A3',50,30000,'school']
];
const imageMap={school:'./public/assets/school-stickers.jpg',kids:'./public/assets/kids-gifts.jpg',portrait:'./public/assets/portraits.jpg',restore:'./public/assets/photo-restoration.jpg',business:'./public/assets/business-print.jpg'};
const serviceImageOverrides={
  'ملصقات مدرسية بصور شخصية':'./public/assets/service-school-stickers.jpg',
  'ملصقات مزخرفة بقص خاص':'./public/assets/service-cut-stickers.jpg',
  'جدول الحصص المدرسية':'./public/assets/service-schedule.jpg',
  'نشرة مدرسية':'./public/assets/service-newsletter.jpg',
  'دفتر مذكرات شخصية':'./public/assets/service-notebook.jpg',
  'صور أطفال ورقية للمغامرات':'./public/assets/service-adventures.jpg',
  'مجلة أطفال مصورة':'./public/assets/service-magazine.jpg',
  'تحسين وترميم الصور':'./public/assets/service-restoration.jpg',
  'صورة شخصية بخلفية بيضاء':'./public/assets/service-studio-portrait.jpg',
  'لوحة بورتريه شخصية':'./public/assets/service-art-portrait.jpg',
  'بورتريه بأسلوب قلم الرصاص':'./public/assets/service-pencil-portrait.jpg',
  'بورتريه بالأقلام الملونة الخشب':'./public/assets/service-colored-portrait.jpg',
  'بورتريه بأسلوب زيتي أو أكريليك':'./public/assets/service-oil-portrait.jpg',
  'لوحة بيانات مولود':'./public/assets/service-baby-board.jpg',
  'بوستر إعلاني للسوشيال ميديا':'./public/assets/service-social-poster.jpg',
  'بوستر توعوي أو إنفوجرافيك':'./public/assets/service-awareness-poster.jpg',
  'مطوية ثلاثية':'./public/assets/service-trifold.jpg',
  'دفتر وصولات':'./public/assets/service-receipt.jpg',
  'بروش دبوس بنز':'./public/assets/service-badge.jpg',
  'بطاقة زفاف':'./public/assets/service-wedding.jpg'
};
const serviceImage=s=>serviceImageOverrides[s[1]]||imageMap[s[6]];
const formatPrice = p => typeof p === 'number' ? `${p.toLocaleString('ar-IQ')} د.ع` : p;
const grid=document.querySelector('#serviceGrid'), resultCount=document.querySelector('#resultCount'), empty=document.querySelector('#emptyState');
let currentCategory='الكل';
function getFiltered(){const q=document.querySelector('#search').value.trim().toLowerCase();return services.filter(s=>(currentCategory==='الكل'||s[0].trim()===currentCategory)&&(!q||s[1].toLowerCase().includes(q)||s[2].toLowerCase().includes(q)));}
function render(){const list=getFiltered();resultCount.textContent=`${list.length} خدمة متاحة`;empty.hidden=list.length!==0;grid.innerHTML=list.map((s,i)=>`<article class="service-card" style="animation-delay:${Math.min(i*25,300)}ms"><div class="service-image"><img src="${serviceImage(s)}" alt="${s[1]}" loading="lazy"></div><div class="service-content"><span class="service-category">${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p><div class="card-bottom"><span class="price">${formatPrice(s[5])} <small>/ ${s[3]}</small></span><button class="request-btn" data-index="${services.indexOf(s)}">اطلب الآن</button></div></div></article>`).join('');document.querySelectorAll('.request-btn').forEach(b=>b.addEventListener('click',()=>openModal(services[Number(b.dataset.index)])));}
function openModal(s){document.querySelector('#modalImage').src=serviceImage(s);document.querySelector('#modalImage').alt=s[1];document.querySelector('#modalCategory').textContent=s[0];document.querySelector('#modalTitle').textContent=s[1];document.querySelector('#modalDesc').textContent=s[2];document.querySelector('#modalPrice').textContent=formatPrice(s[5]);document.querySelector('#modalSpec').textContent=`المقاس: ${s[3]} · العدد: ${s[4]}`;document.querySelector('#modalWhatsapp').href=`https://wa.me/9647706077321?text=${encodeURIComponent(`مرحباً، أريد طلب خدمة: ${s[1]}\nالسعر الظاهر: ${formatPrice(s[5])}\nالمقاس: ${s[3]}\nالعدد: ${s[4]}`)}`;document.querySelector('#modal').classList.add('open');document.querySelector('#modal').setAttribute('aria-hidden','false');}
document.querySelector('#search').addEventListener('input',render);document.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.category').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentCategory=btn.dataset.category;render();}));
document.querySelector('.modal-close').addEventListener('click',()=>document.querySelector('#modal').classList.remove('open'));document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#modal').classList.remove('open')});document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.main-nav').classList.toggle('show'));
render();
